//! The yarn backend for pmpx.
//!
//! Pure mapping: a verb plus its arguments in, one command out. It reads nothing, writes
//! nothing, and never looks at the environment -- everything the plugin is allowed to know
//! arrives in [`Context`], which the host filled in from files it already stat'd.
//!
//! One mapping needs that context: yarn 1.x ("classic") and yarn 2+ ("berry") spell the same
//! operation with different command names, and whether `.yarnrc.yml` was among the matched
//! files is the whole of the difference.

use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

struct Yarn;

impl PackageManager for Yarn {
    fn name(&self) -> &str {
        "yarn"
    }

    fn family(&self) -> Family {
        Family::NODE
    }

    fn command(
        &self,
        ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        let spec = match verb {
            // `yarn install` with a package name is not "add that package"; `add` is a command
            // of its own, and it installs what it adds.
            Verb::Install if args.is_empty() => CommandSpec::new("yarn").arg("install"),
            Verb::Install => CommandSpec::new("yarn").arg("add").args(args.iter()),

            Verb::Remove => CommandSpec::new("yarn").arg("remove").args(args.iter()),

            // No `--` here, or for `build` and `test` below. yarn hands what follows a script
            // name to the script unchanged, so an argument that looks like an option arrives
            // intact:
            //
            //     $ yarn run probe --foo
            //     GOT:--foo
            //
            // `yarn run probe -- --foo` also gets there -- yarn strips the `--` itself -- but
            // there is nothing to strip it for, so the plugin does not add one.
            //
            // pmpx hands over `[target, ...rest]` flattened, so the script name is already the
            // first element of `args` and the whole slice goes through as it is.
            Verb::Run => CommandSpec::new("yarn").arg("run").args(args.iter()),

            Verb::Build => CommandSpec::new("yarn").arg("build").args(args.iter()),

            Verb::Test => CommandSpec::new("yarn").arg("test").args(args.iter()),

            // The one verb the two generations disagree on: berry renamed `upgrade` to `up` and
            // deprecated the old spelling. `.yarnrc.yml` exists only in berry, so the host
            // having matched it decides -- this is a lookup, not a file read.
            //
            // Both arities map the same way: `yarn upgrade` and `yarn upgrade <pkg>...` under
            // classic, `yarn up` and `yarn up <pkg>...` under berry.
            Verb::Update => CommandSpec::new("yarn")
                .arg(if ctx.has_matched(".yarnrc.yml") {
                    "up"
                } else {
                    "upgrade"
                })
                .args(args.iter()),

            // Supported, unlike a backend that has no such subcommand of its own: `yarn exec`
            // resolves a binary from the project's dependencies and runs it, in both
            // generations.
            Verb::Exec => CommandSpec::new("yarn").arg("exec").args(args.iter()),
        };

        Ok(spec)
    }
}

/// The factory that the wrapper crate generated by crate-plugin-kit calls.
pub fn create() -> Box<dyn PackageManager> {
    Box::new(Yarn)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A classic project: the lockfile and the `package.json` every Node tree has, and no
    /// `.yarnrc.yml`.
    fn classic() -> Context {
        Context {
            project_root: PathBuf::from("/tmp/proj"),
            matched: vec!["yarn.lock".to_string(), "package.json".to_string()],
        }
    }

    /// A berry project. `.yarnrc.yml` is strong evidence in the manifest and the plugin's only
    /// signal that this is yarn 2+.
    fn berry() -> Context {
        Context {
            project_root: PathBuf::from("/tmp/proj"),
            matched: vec![
                "yarn.lock".to_string(),
                ".yarnrc.yml".to_string(),
                "package.json".to_string(),
            ],
        }
    }

    /// The exact argv the backend gets spawned with, program first.
    fn argv(ctx: &Context, verb: Verb, args: &[&str]) -> Vec<String> {
        let args: Vec<OsString> = args.iter().map(OsString::from).collect();
        let spec = Yarn.command(ctx, verb, &args).expect("should map");
        std::iter::once(spec.program.to_string_lossy().into_owned())
            .chain(spec.args.iter().map(|a| a.to_string_lossy().into_owned()))
            .collect()
    }

    #[test]
    fn name_and_family_match_the_manifest() {
        assert_eq!(Yarn.name(), "yarn");
        assert_eq!(Yarn.family(), Family::NODE);
    }

    #[test]
    fn install_without_arguments_installs_the_lockfile() {
        assert_eq!(argv(&classic(), Verb::Install, &[]), ["yarn", "install"]);
    }

    #[test]
    fn install_with_arguments_adds_dependencies() {
        assert_eq!(
            argv(&classic(), Verb::Install, &["lodash", "axios"]),
            ["yarn", "add", "lodash", "axios"]
        );
    }

    #[test]
    fn remove_removes_dependencies() {
        assert_eq!(
            argv(&classic(), Verb::Remove, &["lodash"]),
            ["yarn", "remove", "lodash"]
        );
    }

    /// The script name is the first element pmpx hands over, and everything after it belongs to
    /// the script. No `--` is inserted; the comment on the mapping records why.
    #[test]
    fn run_forwards_the_script_name_and_its_arguments_unchanged() {
        assert_eq!(
            argv(&classic(), Verb::Run, &["dev", "--port", "3000"]),
            ["yarn", "run", "dev", "--port", "3000"]
        );
        assert_eq!(
            argv(&classic(), Verb::Run, &["probe", "--foo"]),
            ["yarn", "run", "probe", "--foo"]
        );
    }

    #[test]
    fn build_forwards_its_arguments() {
        assert_eq!(
            argv(&classic(), Verb::Build, &["--mode", "production"]),
            ["yarn", "build", "--mode", "production"]
        );
        assert_eq!(argv(&classic(), Verb::Build, &[]), ["yarn", "build"]);
    }

    #[test]
    fn test_forwards_its_arguments() {
        assert_eq!(
            argv(&classic(), Verb::Test, &["--watch"]),
            ["yarn", "test", "--watch"]
        );
        assert_eq!(argv(&classic(), Verb::Test, &[]), ["yarn", "test"]);
    }

    /// classic spells it `upgrade`, and derives it from a `matched` list without
    /// `.yarnrc.yml`.
    #[test]
    fn update_is_upgrade_without_a_yarnrc_yml() {
        assert_eq!(argv(&classic(), Verb::Update, &[]), ["yarn", "upgrade"]);
        assert_eq!(
            argv(&classic(), Verb::Update, &["lodash"]),
            ["yarn", "upgrade", "lodash"]
        );
    }

    /// Same verb, same arguments, `.yarnrc.yml` matched: berry renamed the command.
    #[test]
    fn update_is_up_with_a_yarnrc_yml() {
        assert_eq!(argv(&berry(), Verb::Update, &[]), ["yarn", "up"]);
        assert_eq!(
            argv(&berry(), Verb::Update, &["lodash"]),
            ["yarn", "up", "lodash"]
        );
    }

    /// The branch is the only thing the context decides: every other verb maps identically in
    /// both generations.
    #[test]
    fn only_update_reads_the_context() {
        for verb in [
            Verb::Install,
            Verb::Remove,
            Verb::Run,
            Verb::Build,
            Verb::Test,
            Verb::Exec,
        ] {
            let args = [OsString::from("x")];
            assert_eq!(
                Yarn.command(&classic(), verb, &args).expect("should map"),
                Yarn.command(&berry(), verb, &args).expect("should map"),
                "{verb} must not depend on which yarn generation this is"
            );
        }
    }

    #[test]
    fn exec_runs_a_dependency_binary() {
        assert_eq!(
            argv(&classic(), Verb::Exec, &["eslint", "."]),
            ["yarn", "exec", "eslint", "."]
        );
        assert_eq!(argv(&berry(), Verb::Exec, &[]), ["yarn", "exec"]);
    }
}
